schemaName: master_only

dataSources:
  ds_master:
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_master
    username: root
    password: root1122.
  ds_slave_0:
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_slave_0
    username: root
    password: root1122.
  ds_slave_1:
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_slave_1
    username: root
    password: root1122.

masterSlaveRule:
  name: ds_ms
  masterDataSourceName: ds_master
  slaveDataSourceNames:
  - ds_slave_0
  - ds_slave_1
